theme: jekyll-theme-minimal
logo: paperwork-logo.png
title: Paperwork
description: Paperwork is an open-source, self-hosted alternative to services like Evernote ®, Microsoft OneNote ® or Google Keep ®
show_downloads: "true"
